"""
Document Format Converter
Converts text content to various document formats (PDF, DOCX, etc.)
"""

import json
from typing import Optional
from pathlib import Path


class DocumentFormatter:
    """Format documents in multiple output formats"""
    
    SUPPORTED_FORMATS = {
        'markdown': 'Markdown (.md)',
        'txt': 'Plain Text (.txt)',
        'pdf': 'PDF Document (.pdf)',
        'docx': 'Word Document (.docx)',
        'html': 'HTML Document (.html)',
        'json': 'JSON Format (.json)',
    }
    
    @staticmethod
    def to_markdown(title: str, content: str) -> str:
        """Convert to Markdown format"""
        return f"# {title}\n\n{content}"
    
    @staticmethod
    def to_plain_text(title: str, content: str) -> str:
        """Convert to Plain Text format"""
        return f"{title.upper()}\n{'=' * len(title)}\n\n{content}"
    
    @staticmethod
    def to_html(title: str, content: str, style: bool = True) -> str:
        """Convert to HTML format"""
        # Convert markdown-style formatting to HTML
        html_content = content.replace('\n\n', '</p><p>')
        html_content = f"<p>{html_content}</p>"
        
        css = """
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                max-width: 900px;
                margin: 0 auto;
                padding: 20px;
                color: #333;
                background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            }
            h1, h2, h3, h4, h5, h6 {
                color: #2c3e50;
                margin-top: 1.5em;
                margin-bottom: 0.5em;
            }
            h1 { border-bottom: 3px solid #3498db; padding-bottom: 10px; }
            h2 { border-bottom: 2px solid #3498db; padding-bottom: 8px; }
            p { margin: 10px 0; }
            ul, ol { margin-left: 20px; }
            li { margin: 5px 0; }
            code {
                background: #f4f4f4;
                padding: 2px 6px;
                border-radius: 3px;
                font-family: 'Monaco', monospace;
            }
            blockquote {
                border-left: 4px solid #3498db;
                margin-left: 0;
                padding-left: 15px;
                color: #666;
            }
            .header { text-align: center; margin-bottom: 30px; }
            .footer { margin-top: 30px; text-align: center; color: #888; font-size: 12px; }
        </style>
        """ if style else ""
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    {css}
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
    </div>
    {html_content}
    <div class="footer">
        <p>Generated by Career Catalyst - AI Job Search Optimizer</p>
    </div>
</body>
</html>"""
        return html
    
    @staticmethod
    def to_json(title: str, content: str, metadata: Optional[dict] = None) -> str:
        """Convert to JSON format"""
        data = {
            'title': title,
            'content': content,
            'format': 'json',
        }
        if metadata:
            data['metadata'] = metadata
        return json.dumps(data, indent=2)
    
    @staticmethod
    def to_docx_content(title: str, content: str) -> dict:
        """Prepare content for DOCX (requires python-docx library)"""
        return {
            'title': title,
            'content': content,
            'format': 'docx',
            'requires_lib': 'python-docx',
        }
    
    @staticmethod
    def to_pdf_content(title: str, content: str) -> dict:
        """Prepare content for PDF (requires reportlab/pypdf library)"""
        return {
            'title': title,
            'content': content,
            'format': 'pdf',
            'requires_lib': 'reportlab',
        }
    
    @classmethod
    def format_document(cls, title: str, content: str, format: str = 'markdown',
                       metadata: Optional[dict] = None) -> str:
        """
        Format document in specified format
        
        Args:
            title: Document title
            content: Document content
            format: Output format (markdown, txt, html, json, docx, pdf)
            metadata: Optional metadata for JSON format
            
        Returns:
            Formatted document as string
        """
        format = format.lower()
        
        if format == 'markdown':
            return cls.to_markdown(title, content)
        elif format == 'txt' or format == 'text':
            return cls.to_plain_text(title, content)
        elif format == 'html':
            return cls.to_html(title, content)
        elif format == 'json':
            return cls.to_json(title, content, metadata)
        elif format == 'docx':
            return cls.to_docx_content(title, content)
        elif format == 'pdf':
            return cls.to_pdf_content(title, content)
        else:
            # Default to markdown
            return cls.to_markdown(title, content)
    
    @staticmethod
    def get_file_extension(format: str) -> str:
        """Get file extension for format"""
        extensions = {
            'markdown': '.md',
            'txt': '.txt',
            'text': '.txt',
            'pdf': '.pdf',
            'docx': '.docx',
            'html': '.html',
            'json': '.json',
        }
        return extensions.get(format.lower(), '.md')


# Helper functions for batch formatting
def format_all_results(results: dict, format: str = 'markdown') -> dict:
    """
    Format all result documents in specified format
    
    Args:
        results: Dictionary with tailored_cv, cover_letter, etc.
        format: Output format
        
    Returns:
        Dictionary with formatted results
    """
    formatter = DocumentFormatter()
    formatted = {}
    
    document_map = {
        'tailored_cv': 'Tailored CV',
        'cover_letter': 'Cover Letter',
        'interview_questions': 'Interview Questions',
        'interview_prep_guide': 'Interview Preparation Guide',
        'skill_gaps': 'Skill Gaps Analysis',
    }
    
    for key, title in document_map.items():
        if key in results and results[key]:
            formatted[key] = formatter.format_document(title, results[key], format)
    
    return formatted


def get_supported_formats() -> dict:
    """Get all supported document formats"""
    return DocumentFormatter.SUPPORTED_FORMATS
